use pantrychef;

CREATE TABLE ingredients (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
category VARCHAR(255) NOT NULL
);

insert into ingredients (name,category) values
('Tomato','Vegetables and Greens'),
('Onion','Vegetables and Greens'),
('Potato','Vegetables and Greens'),
('Capsicum','Vegetables and Greens'),
('Spinach','Vegetables and Greens'),
('Carrot','Vegetables and Greens'),
('Beans','Vegetables and Greens'),
('Broccoli','Vegetables and Greens'),
('Chilli','Vegetables and Greens'),
('Garlic','Vegetables and Greens'),
('Ginger','Vegetables and Greens'),
('Mushroom','Vegetables and Greens'),
('Spinach','Vegetables and Greens'),
('Coriander','Vegetables and Greens'),
('Lettuce','Vegetables and Greens'),
('Fenugreek Leaves','Vegetables and Greens'),
('Green Onions','Vegetables and Greens'),
('Cabbage','Vegetables and Greens'),
('Celery','Vegetables and Greens'),
('Beetroot','Vegetables and Greens'),
('Apple','Fruits'),
('Orange','Fruits'),
('Banana','Fruits'),
('Avocado','Fruits'),
('Mango','Fruits'),
('Lemon','Fruits'),
('Plum','Fruits'),
('Coconut','Fruits'),
('Strawberry','Fruits'),
('Raspberry','Fruits'),
('Blueberry','Fruits'),
('Kiwi','Fruits'),
('Pineapple','Fruits'),
('Cherry','Fruits'),
('Pomegranate','Fruits'),
('Coconut','Fruits'),
('Raisins','Fruits'),
('Pear','Fruits'),
('Passion Fruit','Fruits'),
('Sweet Lime','Fruits'),
('Almonds','Nuts and Seeds'),
('Cashews','Nuts and Seeds'),
('Walnuts','Nuts and Seeds'),
('Raisins','Nuts and Seeds'),
('Hazelnuts','Nuts and Seeds'),
('Pistachio','Nuts and Seeds'),
('Prunes','Nuts and Seeds'),
('Pecans','Nuts and Seeds'),
('Pumpkin Seeds','Nuts and Seeds'),
('Sesame Seeds','Nuts and Seeds'),
('Sunflower Seeds','Nuts and Seeds'),
('Chia Seeds','Nuts and Seeds'),
('Macadamia Nuts','Nuts and Seeds'),
('Anjeer','Nuts and Seeds'),
('Apricot','Nuts and Seeds'),
('Peanuts','Nuts and Seeds'),
('Pine Nuts','Nuts and Seeds'),
('Melon Seeds','Nuts and Seeds'),
('PoppySeeds','Nuts and Seeds'),
('Flax Seeds','Nuts and Seeds'),
('Milk','Dairy'),
('Eggs','Dairy'),
('Fresh Cream','Dairy'),
('Whipped Cream','Dairy'),
('Butter','Dairy'),('Yogurt','Dairy'),
('Buttermilk','Dairy'),
('Cream Cheese','Dairy'),
('Mozzarella Cheese','Dairy'),
('Cheddar Cheese','Dairy'),
('Milk Powder','Dairy'),
('Parmesan Cheese','Dairy'),
('Feta Cheese','Dairy'),
('Sour Cream','Dairy'),
('Greek Yogurt','Dairy'),
('White Sugar','Sugars and Sweetners'),
('Brown Sugar','Sugars and Sweetners'),
('Sweetened Condensed Milk','Sugars and Sweetners'),
('Honey','Sugars and Sweetners'),
('Maple Syrup','Sugars and Sweetners'),
('Stevia','Sugars and Sweetners'),
('Coconut Sugar','Sugars and Sweetners'),
('Jaggery','Sugars and Sweetners'),
('Caramel Syrup','Sugars and Sweetners'),
('Chocolate Syrup','Sugars and Sweetners'),
('Salt','Herbs and Spices'),
('Black Pepper','Herbs and Spices'),
('Chilli powder','Herbs and Spices'),
('Turmeric','Herbs and Spices'),
('Oregano','Herbs and Spices'),
('Chilli Flakes','Herbs and Spices'),
('Peri-Peri','Herbs and Spices'),
('Garlic Powder','Herbs and Spices'),
('Onion Powder','Herbs and Spices'),
('Garam Masala','Herbs and Spices'),
('Cumin Powder','Herbs and Spices'),
('Thyme','Herbs and Spices'),
('Rosemary','Herbs and Spices'),
('Mixed Herbs','Herbs and Spices'),
('Cajun Seasoning','Herbs and Spices'),
('Taco Seasoning','Herbs and Spices'),
('Cinnamon','Herbs and Spices'),
('Cloves','Herbs and Spices'),
('Cardamom','Herbs and Spices'),
('Bay Leaf','Herbs and Spices'),
('Almond Milk','Dairy Free and Meat Substitutes'),
('Oat Milk','Dairy Free and Meat Substitutes'),
('Tofu','Dairy Free and Meat Substitutes'),
('Soy Milk','Dairy Free and Meat Substitutes'),
('Almond Butter','Dairy Free and Meat Substitutes'),
('Coconut Cream','Dairy Free and Meat Substitutes'),
('Tempeh','Dairy Free and Meat Substitutes'),
('Coconut Milk','Dairy Free and Meat Substitutes'),
('Cashew Butter','Dairy Free and Meat Substitutes'),
('Pistachio Butter','Dairy Free and Meat Substitutes'),
('White Rice','Grains and Cereals'),
('Semolina','Grains and Cereals'),
('Oats','Grains and Cereals'),
('Wheat','Grains and Cereals'),
('Brown Rice','Grains and Cereals'),
('Qunioa','Grains and Cereals'),
('Moong Dal','Legumes'),
('Chana Dal','Legumes'),
('Urad Dal','Legumes'),
('Toor Dal','Legumes'),
('Moong','Legumes'),
('Black Chana','Legumes'),
('Chickpea','Legumes'),
('Rajma','Legumes'),
('Masoor Dal','Legumes'),
('Moong Dal','Legumes'),
('Lobia Beans','Legumes'),
('Oil','Oils and Fats'),
('Ghee','Oils and Fats'),
('Butter','Oils and Fats'),
('Olive Oil','Oils and Fats'),
('Mayonaise','Dressings and Vinegars'),
('White vinegar','Dressings and Vinegars'),
('Balsamic Vinegar','Dressings and Vinegars'),
('Sweet Chilli Sauce','Dressings and Vinegars'),
('Soy Sauce','Dressings and Vinegars'),
('Green Chilli Sauce','Dressings and Vinegars'),
('Tomato Ketchup','Dressings and Vinegars'),
('Pizza Pasta Sauce','Sauces Spreads and Dips'),
('Bbq Sauce','Sauces Spreads and Dips'),
('Pesto Sauce','Sauces Spreads and Dips'),
('Harissa Sauce','Sauces Spreads and Dips'),
('Cheese Sauce','Sauces Spreads and Dips'),
('Salsa','Sauces Spreads and Dips'),
('Tahini','Sauces Spreads and Dips'),
('Mustard Sauce','Sauces Spreads and Dips'),
('Schezwan Sauce','Sauces Spreads and Dips'),
('Chipotle Sauce','Sauces Spreads and Dips'),
('Flour','Baking'),
('Vanilla Extract','Baking'),
('Baking Powder','Baking'),
('Baking Soda','Baking'),
('Cornstarch','Baking'),
('Chocolate','Baking'),
('Cookie','Baking'),
('Cocoa powder','Baking'),
('Coffee','Baking'),
('Coconut','Baking'),
('Pasta','Packaged Foods'),
('Noodles','Packaged Foods'),
('Poha','Packaged Foods'),
('Murmura','Packaged Foods'),
('Bread Crumbs','Packaged Foods'),
('Bread','Packaged Foods');

create table recipes (
id int auto_increment primary key,
name varchar(255) not null,
image_url varchar(500),
cooking_time int not null
);
CREATE TABLE recipe_ingredients (
id INT AUTO_INCREMENT PRIMARY KEY,
recipe_id INT,
ingredient_id INT,
quantity DECIMAL(5,2),
unit VARCHAR(50)
);
create table instructions (
id int auto_increment primary key,
recipe_id int,
step_number int not null,
instruction text not null,
foreign key (recipe_id) references recipes(id) on delete cascade
);

INSERT INTO recipes (name, image_url) VALUES
('Red Sauce Pasta','images/red_sauce_pasta.jpg'),
('Stir Fry Veggies','images/stir_fry_veggies.jpg'),
('Schezwan Noodles','images/Schezwan_noodles.jpg'),
('Fruit Salad','images/Fruit_Salad.jpg'),
('Chocolate Cake','images/chocolate_cake.jpg'),
('Cheesecake','images/cheesecake.jpg'),
('Tofu Biryani','images/tofu_biryani.jpg'),
('Vegan Milkshake','images/vegan_milkshake.jpg'),
('Mix Veg Sabzi Roti','images/mix_veg_sabzi_roti.jpg'),
('Pizza','images/pizza.jpg'),
('Sandwich','images/sandwich.jpg'),
('Berry Milkshake','images/berry_milkshake.jpg'),
('Aloo Paratha','images/aloo_paratha.jpg'),
('Salad','images/salad.jpg'),
('Hummus and Pita','images/Hummus_Pita.jpg'),
('Avocado Toast','images/avocado_toast.jpg'),
('French Toast','images/french_toast.jpg'),
('Pancake','images/Pancake.jpg'),
('Dal Chawal','images/dal_chawal.jpg'),
('Banana Bread','images/banana_bread.jpg'),
('Plum Cake','images/plum_cake.jpg'),
('Smoothie bowl','images/smoothie_bowl.jpg'),
('Gajar Halwa','images/Gajar_halwa.jpg'),
('Rasmalai','images/rasmalai.jpg'),
('Idli Sambar','images/idli_sambar.jpg'),
('Moong Dal Cheela','images/moong_dal_cheela.jpg'),
('Tomato Soup','images/tomato_soup.jpg'),
('Manchow Soup','images/manchow_soup.jpg'),
('Dry Fruit Laddoo','images/laddoo.jpg'),
('Poha','images/poha.jpg'),
('Upma','images/upma.jpg'),
('French Fries','images/french_fries.jpg'),
('Pecan pie','images/pecan_pie.jpg'),
('Apple Crumble','images/apple_crumble.jpg'),
('Nimbu paani','images/nimbu_paani.jpg'),
('Fruit Juice','images/fruit_juice.jpg'),
('Pani Puri','images/Pani_puri.jpg'),
('Tacos','images/tacos.jpg'),
('Waffles','images/waffles.jpg'),
('Dhokla','images/dhokla.jpg'),
('Chickpea Salad','images/chickpea_salad.jpg'),
('Crispy Tofu','images/Crispy_tofu.jpg'),
('Tempeh fry','images/tempeh_fry.jpg'),
('Chai Paokde','images/chai_pakode.jpg'),
('Dalgona Coffee','images/dalgona_cofee.jpg'),
('Mac and Cheese','images/mac_cheese.jpg'),
('Oatmeal','images/oatmeal.jpg'),
('Chia Pudding','images/chia_pudding.jpg'),
('Cheesy Nachos','images/cheesy_nachos.jpg'),
('Khichdi','images/khichdi.jpg')
;

INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity, unit) VALUES 
(1,1,2,'pieces'),
(1,2,1,'pieces'),
(1,10,5,'cloves'),
(1,69,1,'cup'),
(1,86,2,'tsp'),
(1,87,1,'tsp'),
(1,90,1,'tsp'),
(1,91,1,'tsp'),
(1,99,1,'tsp'),
(1,144,1,'tbsp'),

(2, 1, 1, 'pieces'), 
(2, 2, 1, 'pieces'), 
(2, 4, 1, 'pieces'), 
(2, 6, 1, 'pieces'), 
(2, 7, 1, 'cup'), 
(2, 8, 1, 'cup'), 
(2, 9, 3, 'pieces'), 
(2, 10, 5, 'cloves'), 
(2, 11, 1, 'tsp'), 
(2, 12, 5, 'pieces'), 
(2, 17, 1, 'tbsp'), 
(2, 18, 1, 'cup'), 
(2, 87, 1, 'tsp'), 
(2, 108, 100, 'grams'), 
(2, 138, 1, 'tsp'), 
(2, 140, 1, 'tsp'), 
(2, 141, 1, 'tsp'), 
(2, 142, 1, 'tsp'), 
(2, 152, 1, 'tsp'),

(3,165,1,'packet'),
(3,1,1,'pieces'),
(3,2,1,'pieces'),
(3,4,1,'pieces'),
(3,6,1,'pieces'),
(3,7,1,'cup'),
(3,8,1,'cup'),
(3,9,3,'pieces'),
(3,10,5,'cloves'),
(3,11,1,'tsp'),
(3,12,5,'pieces'),
(3,17,1,'tbsp'),
(3,18,1,'cup'),
(3,87,1,'tsp'),
(3,108,100,'grams'),
(3,138,1,'tsp'),
(3,140,1,'tsp'),
(3,141,1,'tsp'),
(3,142,1,'tsp'),
(3,152,1,'tsp'),

(4,21,1,'pieces'),
(4,22,1,'pieces'),
(4,23,1,'pieces'),
(4,25,1,'pieces'),
(4,26,1,'pieces'),
(4,27,1,'pieces'),
(4,28,1,'pieces'),
(4,29,1,'pieces'),
(4,30,1,'pieces'),
(4,31,1,'pieces'),
(4,32,1,'pieces'),
(4,33,1,'pieces'),
(4,35,1,'pieces'),
(4,38,1,'pieces'),

(5,154,1,'cup'),
(5,155,1,'tsp'),
(5,156,1,'tsp'),
(5,157,1,'tsp'),
(5,159,1,'cup'),
(5,161,1,'tbsp'),
(5,162,1,'tsp'),
(5,62,1,'pieces'),
(5,61,1,'cup'),
(5,76,1,'cup'),

(6, 61, 1, 'tbsp'),
(6, 64, 1, 'cup'),
(6, 76, 1, 'cup'),
(6, 68, 4, 'tbsp'),
(6, 160, 6, 'pieces'),
(6, 65, 2, 'tbsp'),
(6, 31, 1, 'cup'),

(7, 1, 1, 'pieces'),
(7, 2, 1, 'pieces'),
(7, 3, 1, 'pieces'),
(7, 4, 1, 'pieces'),
(7, 6, 1, 'pieces'),
(7, 9, 3, 'pieces'),
(7, 10, 1, 'tsp'),
(7, 11, 5, 'cloves'),
(7, 66, 2, 'tbsp'),
(7, 86, 1, 'tbsp'),
(7, 88, 1, 'tbsp'),
(7, 89, 1, 'tsp'),
(7, 95, 1, 'tbsp'),
(7, 96, 1, 'tbsp'),
(7, 102, 1, 'pieces'),
(7, 103, 2, 'pieces'),
(7, 104, 2, 'pieces'),
(7, 105, 1, 'pieces'),
(7, 116, 1, 'cup'),
(7, 108, 100, 'grams'),
 
(8, 29, 5, 'pieces'),
(8, 30, 5, 'pieces'),
(8, 31, 5, 'pieces'),
(8, 76, 12, 'tbsp'),
(8, 106, 1, 'cup'),

(9, 1, 1, 'pieces'),
(9, 2, 1, 'pieces'),
(9, 3, 1, 'pieces'),
(9, 6, 1, 'pieces'),
(9, 7, 1, 'pieces'),
(9, 5, 1, 'cup'),
(9, 86, 1, 'tsp'),
(9, 88, 1, 'tbsp'),
(9, 89, 1, 'tsp'),
(9, 95, 1, 'tsp'),
(9, 96, 1, 'tsp'),
(9, 133, 1, 'tbsp'),
(9, 154, 1, 'cup'),
	
(10, 154, 1, 'cup'),
(10, 156, 1, 'tsp'),
(10, 157, 1, 'tsp'),
(10, 144, 1, 'tbsp'),
(10, 135, 1, 'tbsp'),
(10, 69, 1, 'cup'),
(10, 2, 1, 'pieces'),
(10, 3, 1, 'pieces'),
(10, 90, 1, 'tsp'),
(10, 91, 1, 'tsp'),
(10, 97, 1, 'tsp'),
(10, 98, 1, 'tsp'),
	
(11, 1, 1, 'pieces'),
(11, 2, 1, 'pieces'),
(11, 4, 1, 'pieces'),
(11, 1, 1, 'pieces'),
(11, 20, 1, 'pieces'),
(11, 1, 1, 'pieces'),
(11, 69, 1, 'tbsp'),
(11, 70, 1, 'tbsp'),
(11, 86, 1, 'tsp'),
(11, 99, 1, 'tsp'),
(11, 1, 1, 'pieces'),
(11, 134, 1, 'tbsp'),
(11, 137, 1, 'tbsp'),
(11, 147, 1, 'tbsp'),
(11, 153, 1, 'tbsp'),
(11, 169, 1, 'packet'),

(12, 29, 3, 'pieces'),
(12, 30, 3, 'pieces'),
(12, 31, 3, 'pieces'),
(12, 36, 3, 'tbsp'),
(12, 41, 3, 'pieces'),
(12, 42, 3, 'pieces'),
(12, 43, 3, 'pieces'),
(12, 52, 1, 'tbsp'),
(12, 61, 1, 'cup'),
(12, 63, 1, 'tbsp'),
(12, 76, 3, 'tbsp'),

(13, 3, 3, 'pieces'),
(13, 2, 1, 'pieces'),
(13, 9, 3, 'pieces'),
(13, 86, 1, 'tbsp'),
(13, 88, 1, 'tsp'),
(13, 89, 1, 'tsp'),
(13, 95, 1, 'tsp'),
(13, 96, 1, 'tsp'),
(13, 86, 1, 'tsp'),
(13, 134, 2, 'tbsp'),
(13, 86, 1, 'tsp'),
(13, 154, 1, 'cup'),

(14, 1, 1, 'pieces'),
(14, 2, 1, 'pieces'),
(14, 5, 1, 'cup'),
(14, 15, 1, 'cup'),
(14, 4, 1, 'pieces'),
(14, 1, 1, 'pieces'),
(14, 18, 1, 'cup'),
(14, 73, 4, 'tbsp'),
(14, 121, 3, 'tbsp'),
(14, 108, 50, 'grams'),
(14, 139, 1, 'tbsp'),
(14, 86, 1, 'tbsp'),
(14, 87, 1, 'tsp'),
(14, 133, 1, 'tbsp'),
(14, 150, 1, 'tsp'),
(14, 26, 1, 'tsp'),

(15, 128, 1, 'cup'),
(15, 10, 5, 'cloves'),
(15, 26, 1, 'tbsp'),
(15, 128, 1, 'cup'),
(15, 86, 1, 'tbsp'),
(15, 136, 2, 'tbsp'),

(16, 1, 1, 'pieces'),
(16, 2, 1, 'pieces'),
(16, 9, 3, 'pieces'),
(16, 24, 1, 'pieces'),
(16, 26, 1, 'tsp'),
(16, 86, 1, 'tbsp'),
(16, 87, 1, 'tsp'),
(16, 92, 1, 'tsp'),
(16, 14, 1, 'tbsp'),
(16, 135, 1, 'tbsp'),
(16, 169, 1, 'packet'),

(17, 169, 5, 'pieces'),
(17, 61, 4, 'tbsp'),
(17, 62, 1, 'pieces'),
(17, 64, 1, 'tbsp'),
(17, 80, 1, 'tbsp'),
(17, 85, 1, 'tbsp'),
(17, 76, 1, 'tbsp'),
(17, 135, 1, 'tbsp'),

(18, 154, 1, 'cup'),
(18, 156, 1, 'tsp'),
(18, 135, 1, 'tbsp'),
(18, 61, 4, 'tbsp'),
(18, 62, 1, 'pieces'),
(18, 76, 4, 'tbsp'),
(18, 80, 1, 'tbsp'),

(19, 116, 1, 'cup'),
(19, 125, 1, 'cup'),
(19, 133, 1, 'tbsp'),
(19, 1, 1, 'pieces'),
(19, 1, 2, 'pieces'),
(19, 9, 3, 'pieces'),
(19, 10, 1, 'tsp'),
(19, 11, 1, 'tsp'),
(19, 14, 1, 'tbsp'),
(19, 86, 1, 'tbsp'),
(19, 88, 1, 'tbsp'),
(19, 89, 1, 'tsp'),
(19, 96, 1, 'tsp'),
(19, 134, 1, 'tbsp'),

(20, 23, 1, 'pieces'),
(20, 23, 1, 'pieces'),
(20, 44, 1, 'tsp'),
(20, 61, 1, 'cup'),
(20, 65, 1, 'tbsp'),
(20, 76, 1, 'tbsp'),
(20, 77, 1, 'tbsp'),
(20, 154, 1, 'cup'),
(20, 155, 1, 'tsp'),
(20, 156, 1, 'tsp'),
(20, 157, 1, 'tsp'),
(20, 159, 1, 'tbsp'),

(21, 27, 1, 'pieces'),
(21, 23, 1, 'pieces'),
(21, 44, 1, 'tsp'),
(21, 41, 1, 'tsp'),
(21, 42, 1, 'tsp'),
(21, 43, 1, 'tsp'),
(21, 45, 1, 'tsp'),
(21, 46, 1, 'tsp'),
(21, 47, 1, 'tsp'),
(21, 49, 1, 'tsp'),
(21, 50, 1, 'tsp'),
(21, 61, 1, 'cup'),
(21, 65, 1, 'tbsp'),
(21, 76, 1, 'tbsp'),
(21, 77, 1, 'tbsp'),
(21, 154, 1, 'cup'),
(21, 155, 1, 'tsp'),
(21, 156, 1, 'tsp'),
(21, 157, 1, 'tsp'),
(21, 159, 1, 'tbsp'),

(22, 44, 1, 'tsp'),
(22, 41, 1, 'tsp'),
(22, 42, 1, 'tsp'),
(22, 43, 1, 'tsp'),
(22, 45, 1, 'tsp'),
(22, 46, 1, 'tsp'),
(22, 47, 1, 'tsp'),
(22, 49, 1, 'tsp'),
(22, 50, 1, 'tsp'),
(22, 51, 1, 'tsp'),
(22, 52, 1, 'tsp'),
(22, 61, 1, 'cup'),
(22, 79, 1, 'tbsp'),
(22, 107, 1, 'cup'),
(22, 29, 3, 'pieces'),
(22, 30, 3, 'pieces'),
(22, 31, 3, 'pieces'),
(22, 23, 1, 'pieces'),

(23, 6, 2, 'pieces'),
(23, 41, 1, 'tsp'),
(23, 61, 3, 'cup'),
(23, 104, 1, 'tsp'),
(23, 134, 3, 'tbsp'),
(23, 76, 1, 'cup'),

(24, 61, 2, 'cup'),
(24, 63, 1, 'cup'),
(24, 41, 1, 'tsp'),
(24, 46, 1, 'tsp'),
(24, 76, 2, 'cup'),
(24, 26, 2, 'tsp'),

(25, 117, 1, 'cup'),
(25, 66, 2, 'tbsp'),
(25, 157, 1, 'tsp'),
(25, 125, 1, 'cup'),
(25, 1, 1, 'pieces'),
(25, 2, 1, 'pieces'),
(25, 9, 1, 'pieces'),
(25, 10, 1, 'tsp'),
(25, 86, 1, 'tbsp'),
(25, 88, 1, 'tsp'),
(25, 89, 1, 'tsp'),
(25, 96, 1, 'tsp'),

(26, 131, 1, 'cup'),
(26, 9, 1, 'pieces'),
(26, 10, 1, 'tsp'),
(26, 86, 1, 'tbsp'),
(26, 5, 1, 'tbsp'),
(26, 133, 1, 'tbsp'),
    
(27, 1, 3, 'pieces'),
(27, 10, 3, 'cloves'),
(27, 63, 1, 'tbsp'),
(27, 86, 1, 'tbsp'),
(27, 87, 1, 'tsp'),
(27, 99, 1, 'tbsp'),
(27, 135, 1, 'tbsp'),

(28, 1, 1, 'pieces'),
(28, 2, 1, 'pieces'),
(28, 4, 1, 'pieces'),
(28, 6, 1, 'pieces'),
(28, 7, 1, 'cup'),
(28, 8, 1, 'cup'),
(28, 9, 3, 'pieces'),
(28, 10, 5, 'cloves'),
(28, 11, 1, 'tsp'),
(28, 17, 1, 'tbsp'),
(28, 18, 1, 'cup'),
(28, 87, 1, 'tsp'),
(28, 138, 1, 'tsp'),
(28, 140, 1, 'tsp'),
(28, 141, 1, 'tsp'),
(28, 142, 1, 'tsp'),
(28, 152, 1, 'tsp'),
    
(29, 41, 1, 'tbsp'),
(29, 42, 1, 'tbsp'),
(29, 43, 1, 'tbsp'),
(29, 44, 1, 'tbsp'),
(29, 45, 1, 'tbsp'),
(29, 46, 1, 'tbsp'),
(29, 47, 1, 'tbsp'),
(29, 48, 1, 'tbsp'),
(29, 49, 1, 'tbsp'),
(29, 50, 1, 'tbsp'),
(29, 51, 1, 'tbsp'),
(29, 134, 5, 'tbsp'),

(30, 166, 1, 'cup'),
(30, 2, 1, 'pieces'),
(30, 9, 3, 'pieces'),
(30, 14, 1, 'tbsp'),
(30, 56, 1, 'tbsp'),
(30, 86, 1, 'tbsp'),
(30, 89, 1, 'tsp'),

(31, 177, 1, 'cup'),
(31, 2, 1, 'pieces'),
(31, 9, 3, 'pieces'),
(31, 14, 1, 'tbsp'),
(31, 56, 1, 'tbsp'),
(31, 86, 1, 'tbsp'),
(31, 124, 1, 'tbsp'),

(32, 3, 3, 'pieces'),
(32, 86, 1, 'tsp'),
(32, 92, 1, 'tsp'),

(33, 48, 3, 'tbsp'),
(33, 66, 3, 'tbsp'),
(33, 76, 4, 'tbsp'),
(33, 154, 1, 'cup'),
(33, 156, 1, 'tbsp'),
(33, 157, 1, 'tsp'),

(34, 21, 3, 'pieces'),
(34, 66, 3, 'tbsp'),
(34, 76, 4, 'tbsp'),
(34, 48, 3, 'tbsp'),
(34, 154, 1, 'cup'),

(35, 26, 3, 'tbsp'),
(35, 76, 1, 'tbsp'),
(35, 86, 1, 'tsp'),
(35, 87, 1, 'tsp'),

(36, 22, 1, 'pieces'),
(36, 25, 1, 'pieces'),
(36, 35, 1, 'pieces'),
(36, 40, 1, 'pieces'),
(36, 33, 1, 'pieces'),

(37, 2, 1, 'pieces'),
(37, 2, 2, 'pieces'),
(37, 14, 1, 'tbsp'),
(37, 9, 3, 'pieces'),
(37, 10, 1, 'tsp'),
(37, 86, 1, 'tbsp'),
(37, 127, 1, 'cup'),

(38, 2, 1, 'pieces'),
(38, 1, 1, 'pieces'),
(38, 9, 3, 'pieces'),
(38, 14, 1, 'tbsp'),
(38, 26, 1, 'pieces'),
(38, 24, 1, 'pieces'),
(38, 86, 1, 'tbsp'),
(38, 101, 1, 'tbsp'),
(38, 70, 1, 'tbsp'),
(38, 74, 1, 'tbsp'),
(38, 139, 1, 'cup'),
(38, 15, 3, 'tbsp'),

(39, 61, 1, 'cup'),
(39, 62, 1, 'piece'),
(39, 64, 1, 'tbsp'),
(39, 76, 3, 'tbsp'),
(39, 154, 1, 'cup'),
(39, 155, 1, 'tsp'),
(39, 156, 1, 'tsp'),
(39, 157, 1, 'tsp'),
(39, 80, 1, 'tbsp'),
(39, 84, 1, 'tbsp'),
(39, 85, 1, 'tbsp'),
(39, 29, 1, 'pieces'),
(39, 30, 1, 'pieces'),
(39, 31, 1, 'pieces'),

(40, 117, 1, 'cup'),
(40, 66, 3, 'tbsp'), 
(40, 157, 1, 'tsp'),
(40, 9, 1, 'pieces'),
(40, 86, 1, 'tbsp'),
(40, 133, 1, 'tbsp'),

(41, 128, 1, 'cup'),
(41, 1, 1, 'pieces'),
(41, 2, 1, 'pieces'),
(41, 9, 1, 'pieces'),
(41, 14, 1, 'tbsp'),
(41, 15, 1, 'cup'),
(41, 20, 1, 'pieces'),
(41, 26, 1, 'pieces'),
(41, 73, 2, 'tbsp'),
(41, 86, 1, 'tbsp'),
(41, 87, 1, 'tsp'),
(41, 94, 1, 'tsp'),
(41, 95, 1, 'tsp'),
(41, 136, 1, 'tbsp'),
(41, 139, 1, 'tbsp'),
(41, 151, 1, 'tsp'),

(42, 108, 100, 'grams'),
(42, 1, 1, 'pieces'),
(42, 2, 1, 'pieces'),
(42, 4, 1, 'pieces'),
(42, 6, 1, 'pieces'),
(42, 7, 1, 'cup'),
(42, 8, 1, 'cup'),
(42, 9, 3, 'pieces'),
(42, 10, 5, 'cloves'),
(42, 11, 1, 'tsp'),
(42, 12, 5, 'pieces'),
(42, 17, 1, 'tbsp'),
(42, 18, 1, 'cup'),
(42, 158, 1, 'tbsp'),
(42, 87, 1, 'tsp'),
(42, 138, 1, 'tsp'),
(42, 140, 1, 'tsp'),
(42, 141, 1, 'tsp'),
(42, 142, 1, 'tsp'),
(42, 152, 1, 'tsp'),

(43, 112, 100, 'grams'),
(43, 1, 1, 'pieces'),
(43, 2, 1, 'pieces'),
(43, 4, 1, 'pieces'),
(43, 6, 1, 'pieces'),
(43, 7, 1, 'cup'),
(43, 8, 1, 'cup'),
(43, 9, 3, 'pieces'),
(43, 10, 5, 'cloves'),
(43, 11, 1, 'tsp'),
(43, 12, 5, 'pieces'),
(43, 17, 1, 'tbsp'),
(43, 18, 1, 'cup'),
(43, 158, 1, 'tbsp'),
(43, 87, 1, 'tsp'),
(43, 138, 1, 'tsp'),
(43, 140, 1, 'tsp'),
(43, 141, 1, 'tsp'),
(43, 142, 1, 'tsp'),
(43, 152, 1, 'tsp'),

(44, 61, 1, 'cup'),
(44, 76, 2, 'tbsp'),
(44, 123, 1, 'cup'),
(44, 16, 1, 'cup'),
(44, 9, 3, 'pieces'),
(44, 86, 1, 'tbsp'),

(45, 61, 1, 'cup'),
(45, 76, 2, 'tbsp'),
(45, 162, 1, 'tbsp'),

(46, 164, 1, 'cup'),
(46, 31, 1, 'cup'),
(46, 65, 1, 'tbsp'),
(46, 69, 2, 'tbsp'),
(46, 70, 2, 'tbsp'),
(46, 86, 1, 'tsp'),
(46, 90, 1, 'tsp'),
(46, 91, 1, 'tsp'),
(46, 99, 1, 'tsp'),
    
(47, 118, 1, 'cup'),
(47, 79, 1, 'tbsp'),
(47, 161, 1, 'tbsp'),
(47, 29, 1, 'pieces'),
(47, 30, 1, 'pieces'),
(47, 31, 1, 'pieces'),
(47, 49, 1, 'tbsp'),
(47, 50, 1, 'tbsp'),
(47, 52, 1, 'tbsp'),
(47, 61, 4, 'tbsp'),

(48, 52, 3, 'tbsp'),
(48, 61, 3, 'tbsp'),
(48, 79, 1, 'tbsp'),
(48, 161, 1, 'tbsp'),
(48, 29, 1, 'pieces'),
(48, 30, 1, 'pieces'),
(48, 31, 1, 'pieces'),
(48, 49, 1, 'tbsp'),
(48, 50, 1, 'tbsp'),
    
(49, 1, 1, 'pieces'),
(49, 2, 1, 'pieces'),
(49, 69, 1, 'tbsp'),
(49, 70, 1, 'tbsp'),
(49, 74, 1, 'tbsp'),
(49, 149, 1, 'tbsp'),
(49, 24, 1, 'pieces'),
(49, 26, 1, 'pieces'),
(49, 86, 1, 'tbsp'),
    
(50, 119, 1, 'cup'),
(50, 131, 4, 'tbsp'),
(50, 86, 1, 'tbsp'),
(50, 89, 1, 'tsp'),
(50, 134, 1, 'tbsp');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(1, 1, 'Bring water to a boil and add the pasta along with salt.'),
(1, 2, 'Cook the pasta until al dente.'),
(1, 3, 'Cook the tomatoes in boiling water for 5 mins.'),
(1, 4, 'For the red sauce, saute onions and garlic in olive oil.'),
(1, 5, 'Once tomatoes are done, remove the skin and make a puree.'),
(1, 6, 'Add the tomatoe puree once the onions turn translucent.'),
(1, 7, 'Cook the tomato puree and add salt, pepper, oregano, chilli flakes and mixed herbs.'),
(1, 8, 'Add the cooked pasta and grate some cheese over it and your pasta is ready to serve.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(2, 1, 'Chop all the vegetables and tofu into cubes.'),
(2, 2, 'Saute the vegetables and tofu in some oil.'),
(2, 3, 'You can also add paneer instead of tofu.'),
(2, 4, 'Now add salt, pepper and all the sauces.'),
(2, 5, 'Cook the veggies until they soft and garnish it with some coriander.'),
(2, 6, 'Your stir fry veggies are ready to eat.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(3, 1, 'Bring water to a boil and then add salt and some oil.'),
(3, 2, 'Add your noodles and cook until soft.'),
(3, 3, 'Once the noodles are cooked, strain them and drizzle some oil over it and keep it aside.'),
(3, 4, 'In a pan, add some oil and add finely chopped garlic, ginger and chilli.'),
(3, 5, 'Add your shredded vegetables and cook them for few minutes.'),
(3, 6, 'Season it with salt and pepper and add your sauces.'),
(3, 7, 'Add schezwan sauce and then add your noodles.'),
(3, 8, 'Toss it well and your schezwan noodles are ready to serve.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(4, 1, 'Chop all your fruits and then add them in a bowl.'),
(4, 2, 'Add some lemon juice. You can also add some chaat masala for a tangy kick.'),
(4, 3, 'Serve your fruit salad and garnish it with some coconut flakes.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(5, 1, 'First prepare your dry mix by combining flour, baking powder, baking soda, cocoa powder and coffee.'),
(5, 2, 'Keep it aside and prepare your wet mix.'),
(5, 3, 'For the wet mix, first whip some butter and sugar together. Once it is nice and fluffy, beat your eggs and combine everything well.'),
(5, 4, 'Add vanilla extract and mix everything together.'),
(5, 5, 'Gently sift in your dry ingredients and combine everything well.'),
(5, 6, 'Add milk to adjust the consistency.'),
(5, 7, 'Make sure you do not overmix the batter.'),
(5, 8, 'In the meantime, preheat your oven for 10 mins.'),
(5, 9, 'Pour the batter in the cake tin.'),
(5, 10, 'Bake your cake in the oven at 180°C for around 20-25 minutes.'),
(5, 11, 'Once the cake is baked, let it cool down and then you can decorate your cake with some whipped cream and chocolate.'),
(5, 12, 'Your cake is ready to be served.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(6, 1, 'Crush the biscuits and add some melted butter to it.'),
(6, 2, 'Add the biscuit base to the cake tin.'),
(6, 3, 'Let the base set for a few minutes in the refrigerator.'),
(6, 4, 'In the meantime, whip your cream cheese and whipped cream separately.'),
(6, 5, 'Combine your cream cheese and whipped cream along with some sugar and vanilla extract.'),
(6, 6, 'Pour the mixture over the biscuit base and refrigerate it for a few hours.'),
(6, 7, 'Prepare a blueberry compote by cooking blueberries with sugar and some lemon zest.'),
(6, 8, 'Once the cheesecake is set, pour the blueberry compote and garnish it with some blueberries.'),
(6, 9, 'Your cheesecake is ready to eat.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(7, 1, 'Cube up your tofu and veggies.'),
(7, 2, 'Marinate your tofu with curd, all the spices, and ginger-garlic-chili paste.'),
(7, 3, 'Let it marinate for an hour.'),
(7, 4, 'Meanwhile, boil water and add salt and whole spices.'),
(7, 5, 'Once water comes to a rolling boil, add your rice and cook it until soft.'),
(7, 6, 'In another pan, sauté garlic, chili, and ginger.'),
(7, 7, 'Add your onions, and once they are soft, add all other veggies along with some salt and spices.'),
(7, 8, 'Add the marinated tofu and let it cook.'),
(7, 9, 'Now remove half of the vegetables and add a layer of cooked rice. Also, sprinkle some chopped coriander, mint, and saffron water.'),
(7, 10, 'Add the remaining vegetable gravy followed by rice, and garnish with chopped coriander, mint, saffron water, fried onion, and some ghee.'),
(7, 11, 'Now cover the pot and let it cook for 5-10 minutes.'),
(7, 12, 'Now serve your biryani with some raita.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(8, 1, 'Take a blender jar and add your berries to it.'),
(8, 2, 'Add some sugar to it and pour oat milk into it.'),
(8, 3, 'You can also add almond milk, soy milk, or coconut milk instead of oat milk.'),
(8, 4, 'Then garnish it with some more chopped berries.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(9, 1, 'First, chop all the veggies.'),
(9, 2, 'In a pan, add some oil along with onions.'),
(9, 3, 'Add your veggies along with salt and spices.'),
(9, 4, 'Cook your veggies until soft and garnish them with some coriander.'),
(9, 5, 'To make your roti, combine flour and some salt, and make a dough out of it.'),
(9, 6, 'Roll out your rotis and serve them with mixed veg sabzi.'),
(9, 7, 'Your mixed veg sabzi with roti is ready to eat.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(10, 1, 'First, make the pizza base.'),
(10, 2, 'For the pizza base dough, combine flour, curd, baking soda, and baking powder.'),
(10, 3, 'Let the dough rest for a few minutes, and in the meantime, prepare your pizza sauce.'),
(10, 4, 'For the pizza sauce, heat up some oil and sauté garlic and onions.'),
(10, 5, 'Add the tomato puree, salt, pepper, oregano, chili flakes, and pasta pizza sauce, then mix well.'),
(10, 6, 'Roll out the pizza base, add your sauce, toppings, and lots of cheese.'),
(10, 7, 'Bake the pizza in the oven for 10 minutes and serve hot.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(11, 1, 'Chop up some onions, tomatoes, and capsicum into dices.'),
(11, 2, 'Add all the veggies into a bowl and mix in salt and mixed herbs.'),
(11, 3, 'In a bowl, combine mayonnaise, harissa sauce, and chipotle sauce.'),
(11, 4, 'On one slice of bread, spread the prepared sauce mix, add the topping mix, and cover with another slice of bread.'),
(11, 5, 'Toast the bread with some ghee or butter on both sides in a pan and serve hot with some green chutney.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(12, 1, 'Chop up your berries.'),
(12, 2, 'Chop your almonds, cashews, walnuts, and all the seeds.'),
(12, 3, 'In a blender jar, add milk, cream, and berries.'),
(12, 4, 'Garnish with chopped nuts and seeds, and serve it chilled.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(13, 1, 'Boil your potatoes and mash them.'),
(13, 2, 'To the mashed potatoes, add chopped onions, chillies, ginger, and spices.'),
(13, 3, 'Make the dough using flour, salt, and water.'),
(13, 4, 'Roll your parathas by filling them with the potato mixture.'),
(13, 5, 'Cook your paratha with ghee or butter in a pan.'),
(13, 6, 'Serve it hot with curd, pickle, and chillies.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(14, 1, 'Chop your tomatoes, onions, spinach, lettuce, and cabbage.'),
(14, 2, 'Cook your quinoa.'),
(14, 3, 'Prepare your dressing using olive oil, salt, pepper, mustard sauce, garlic, and lemon.'),
(14, 4, 'Mix your dressing with quinoa and veggies.'),
(14, 5, 'Serve the salad with feta cheese.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(15, 1, 'Cook your soaked chickpeas.'),
(15, 2, 'In a blender jar, add your chickpeas, garlic, cumin, salt, pepper, and ice cubes.'),
(15, 3, 'Blend it and garnish it with olive oil, chili powder, and some chickpeas.'),
(15, 4, 'Serve it with pita bread.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(16, 1, 'Chop some tomatoes, onions, and chillies.'),
(16, 2, 'Mash the avocados and add the tomatoes, onions, chillies, salt, and pepper. Squeeze some lemon juice.'),
(16, 3, 'Add peri peri mix and garnish with some coriander.'),
(16, 4, 'Toast your bread in some ghee or butter and spread your avocado mix on top.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(17, 1, 'In a plate, mix milk, sugar, and egg.'),
(17, 2, 'Dip your bread in the prepared milk mixture.'),
(17, 3, 'Heat some ghee or butter in a pan, then cook the soaked bread properly on both sides.'),
(17, 4, 'Serve it with whipped cream, maple syrup, or chocolate syrup.'),
(17, 5, 'Garnish with berries.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(18, 1, 'Mix flour, egg, sugar, and milk to make the pancake batter.'),
(18, 2, 'Cook the pancake with some butter until golden brown.'),
(18, 3, 'Serve it hot with maple syrup, berries, and whipped cream.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(19, 1, 'Boil water and cook the rice until soft.'),
(19, 2, 'Cook the dal with turmeric, salt, and ghee.'),
(19, 3, 'Chop the tomatoes, onions, garlic, chili, and ginger.'),
(19, 4, 'Heat ghee in a pan, then sauté garlic, ginger, and chili before adding onions.'),
(19, 5, 'Add the tomatoes and spices, then cook until soft.'),
(19, 6, 'Pour in the cooked dal and bring it to a boil.'),
(19, 7, 'Serve the dal hot with rice.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(20, 1, 'Mash the bananas for the banana bread batter.'),
(20, 2, 'Add flour, baking powder, baking soda, and vanilla extract.'),
(20, 3, 'In another bowl, mix butter, white sugar, and brown sugar well.'),
(20, 4, 'Combine the dry ingredients with the sugar mixture and mashed bananas, then mix until smooth.'),
(20, 5, 'Pour the batter into a cake tin and bake for at least 20-25 minutes.'),
(20, 6, 'Serve the banana bread, optionally garnished with nuts.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(21, 1, 'Prepare the dry mix by combining flour, baking soda, baking powder, and sugar.'),
(21, 2, 'In a pan, caramelize some sugar and mix in nuts and dried plums.'),
(21, 3, 'Prepare the wet mix by combining butter, milk, and vanilla extract.'),
(21, 4, 'Combine the wet mix, dry mix, and the caramelized nuts and plums.'),
(21, 5, 'Pour the batter into a cake tin and bake for 20-25 minutes.'),
(21, 6, 'Serve the cake warm.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(22, 1, 'Add chopped fruits to the milk and blend until smooth.'),
(22, 2, 'Add a sweetener of your choice and blend again.'),
(22, 3, 'Pour the smoothie into a bowl and garnish with fruits, nuts, and seeds.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(23, 1, 'Shred the carrots.'),
(23, 2, 'In a pan, add some ghee and roast the carrots until soft.'),
(23, 3, 'Add milk and cook until it reduces.'),
(23, 4, 'Add sugar and continue reducing the milk.'),
(23, 5, 'Stir continuously until the mixture thickens.'),
(23, 6, 'Once the halwa is done, garnish it with dried nuts and serve warm.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(24, 1, 'In a pan, add milk and let it boil.'),
(24, 2, 'Add some lemon juice and let it curdle.'),
(24, 3, 'Strain the curdled milk, add some cornflour, and knead into a dough.'),
(24, 4, 'Shape the dough into small balls and boil them in water.'),
(24, 5, 'To make the rabdi, heat some milk in a pan along with sugar and saffron.'),
(24, 6, 'Let the rabdi boil, then add the rasmalai balls to it.'),
(24, 7, 'Garnish with pistachio shavings and serve chilled.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(25, 1, 'In a bowl, mix semolina, curd, and salt. Let it rest for a few minutes.'),
(25, 2, 'For the sambar, cook the dal until soft.'),
(25, 3, 'In a pan, heat some oil and sauté onions, tomatoes, chilies, ginger, and curry leaves.'),
(25, 4, 'Add the cooked dal and spices, then mix well.'),
(25, 5, 'Let it simmer, then add tamarind water and coriander.'),
(25, 6, 'Steam the idlis and serve them hot with sambar.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(26, 1, 'Soak the moong dal for a few hours.'),
(26, 2, 'In a blender, add soaked moong dal, spinach, chili, ginger, and salt.'),
(26, 3, 'Blend until smooth, then add baking soda and mix well.'),
(26, 4, 'Cook the cheelas in oil or ghee until golden brown and serve hot.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(27, 1, 'Blanch the tomatoes and make a puree.'),
(27, 2, 'In a pan, heat up some oil and add finely chopped garlic and onions.'),
(27, 3, 'Sauté well and add the spices and tomato puree.'),
(27, 4, 'Add cream and cook it well.'),
(27, 5, 'Add oregano, salt, pepper, and serve hot with some basil leaves.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(28, 1, 'Chop onions, carrots, capsicum, beans, cabbage, and other veggies of your choice finely.'),
(28, 2, 'In a pan, heat up some oil and add finely chopped ginger, garlic, and chilies.'),
(28, 3, 'Add the veggies and cook for a few minutes.'),
(28, 4, 'Add soy sauce, chili sauce, vinegar, salt, pepper, and water.'),
(28, 5, 'Add cornflour slurry and cook for a few minutes.'),
(28, 6, 'Serve hot and garnish with some coriander and fried noodles.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(29, 1, 'Chop almonds, cashews, walnuts, raisins, hazelnuts, prunes, pistachios, and pecans finely.'),
(29, 2, 'Roast the nuts and seeds in ghee.'),
(29, 3, 'In another pan, add some ghee, mash some dates, and cook until soft and mashed.'),
(29, 4, 'Add the nuts and seeds and mix well.'),
(29, 5, 'Let the mixture cool a bit, then shape into laddoos and roll them in desiccated coconut.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(30, 1, 'Soak the poha in water and let it sit for a few minutes.'),
(30, 2, 'Chop some onions, chilies, and tomatoes.'),
(30, 3, 'In a pan, sauté the onions, chilies, and tomatoes, then add turmeric and salt.'),
(30, 4, 'Add the poha and cook well.'),
(30, 5, 'Serve the poha hot and garnish it with some coriander.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(31, 1, 'In a pan, roast the semolina.'),
(31, 2, 'Chop the onions, tomatoes, and carrots finely.'),
(31, 3, 'In a pan, add some urad dal and roast well, then add curry leaves, green chilies, onions, and other veggies, and cook until soft.'),
(31, 4, 'Add the roasted semolina and cook everything well.'),
(31, 5, 'Add water and cook the upma.'),
(31, 6, 'Garnish with some coriander and serve hot.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(32, 1, 'Cut the potatoes into fries.'),
(32, 2, 'Fry them until golden brown and season them with peri-peri spice mix.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(33, 1, 'For the pie crust, combine flour, baking powder, melted butter, and milk, and mix well.'),
(33, 2, 'Roll the dough, shape it into the pie crust, and bake in the oven for 20-25 minutes.'),
(33, 3, 'For the pie filling, dry roast pecans.'),
(33, 4, 'In a pan, whisk together sugar, corn syrup, butter, eggs, and vanilla extract.'),
(33, 5, 'Once the crust is baked, pour in the filling along with the roasted pecans and bake in the oven for 20-25 minutes.'),
(33, 6, 'Serve fresh, topped with some cream.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(34, 1, 'Slice your apples into strips.'),
(34, 2, 'Mix milkmaid and butter in a saucepan and heat for 5 minutes.'),
(34, 3, 'Set aside to cool.'),
(34, 4, 'In a greased dish, place the apples in layers.'),
(34, 5, 'Pour the mixture over it and spread it evenly.'),
(34, 6, 'Mix flour, butter, and cinnamon powder to create a crumbly texture.'),
(34, 7, 'Top the apples with the crumble and bake for 40 minutes.'),
(34, 8, 'Serve hot or cold.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(35, 1, 'In a jar, add water and sugar, and stir until dissolved.'),
(35, 2, 'Add lemon juice, a pinch of salt, and pepper.'),
(35, 3, 'You can also add chaat masala for extra flavor.'),
(35, 4, 'Serve chilled with ice cubes.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(36, 1, 'Chop up fruits of your choice.'),
(36, 2, 'Blend them well in a juicer.'),
(36, 3, 'Strain the juice, garnish with mint leaves, and serve cold.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(37, 1, 'For puris, mix semolina with flour and knead a dough.'),
(37, 2, 'For the pani, blend mint leaves, coriander leaves, chilies, ginger, tamarind, salt, and lemon juice.'),
(37, 3, 'Strain the puree and add water to adjust the consistency.'),
(37, 4, 'For the potato filling, mash boiled potatoes, add spices, salt, and mix well.'),
(37, 5, 'Boil the kala chana and mix it with the potato mixture.'),
(37, 6, 'Roll out the puris and fry them until golden brown and crisp.'),
(37, 7, 'To assemble, fill the puris with the potato mixture, add onions and sev, then pour in the pani.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(38, 1, 'For the taco filling, boil rajma in salted water.'),
(38, 2, 'In a pan, heat olive oil and sauté garlic and onions.'),
(38, 3, 'Add tomatoes and let them simmer for a few minutes.'),
(38, 4, 'Add the boiled rajma and the spices.'),
(38, 5, 'Mash the rajma to form a thick filling.'),
(38, 6, 'For the toppings, chop onions, tomatoes, and prepare guacamole.'),
(38, 7, 'To assemble, add the filling to the taco shell, followed by chopped veggies and guacamole.'),
(38, 8, 'Sprinkle cheese over the tacos.'),
(38, 9, 'Garnish with coriander and salsa.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(39, 1, 'To make the waffle batter, mix flour, baking soda, baking powder, and vanilla extract.'),
(39, 2, 'Add milk and whisk until smooth.'),
(39, 3, 'Pour the batter into a preheated waffle maker and cook on both sides with butter.'),
(39, 4, 'Once the waffles are golden and crisp, top them with whipped cream, berries, and maple syrup.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(40, 1, 'To make dhokla, mix semolina, curd, and salt together.'),
(40, 2, 'Let it sit for 20 minutes.'),
(40, 3, 'Add baking soda to the batter, pour it into the tray, and steam for 10-15 minutes.'),
(40, 4, 'Let it cool slightly, then add the curry leaves and chili tempering on top.'),
(40, 5, 'Serve with green chutney.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(41, 1, 'Boil the chickpeas until soft, then let them cool.'),
(41, 2, 'Chop all your favorite vegetables.'),
(41, 3, 'Prepare the dressing with olive oil, mustard sauce, lemon juice, salt, and pepper.'),
(41, 4, 'Coat the chickpeas in spices and roast them in the oven for 10 minutes.'),
(41, 5, 'In a bowl, mix the vegetables, chickpeas, and dressing, then garnish with feta cheese and coriander.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(42, 1, 'Chop the tofu into chunks.'),
(42, 2, 'Prepare the coating by mixing cornflour, spices, salt, and pepper in a bowl.'),
(42, 3, 'Add water and make a slurry to coat the tofu chunks.'),
(42, 4, 'Deep-fry the tofu chunks in hot oil until crispy.'),
(42, 5, 'In a wok, heat oil and sauté ginger, chili, garlic, and onions.'),
(42, 6, 'Add vegetables of your choice, followed by soy sauce, vinegar, and chili sauce.'),
(42, 7, 'Add the fried tofu and mix everything well.'),
(42, 8, 'Serve hot, garnished with coriander and sesame seeds.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(43, 1, 'Chop the tempeh into cubes.'),
(43, 2, 'Prepare the coating by mixing cornflour, spices, salt, and pepper in a bowl.'),
(43, 3, 'Add water to create a slurry and coat the tempeh cubes.'),
(43, 4, 'Deep-fry the coated tempeh in hot oil until crispy.'),
(43, 5, 'In a wok, heat some oil and sauté ginger, chili, garlic, and onions.'),
(43, 6, 'Add vegetables of your choice, then stir in soy sauce, vinegar, and chili sauce.'),
(43, 7, 'Add the fried tempeh and mix everything well.'),
(43, 8, 'Serve hot, garnished with coriander and sesame seeds.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(44, 1, 'In a pan, add tea leaves, sugar, cardamom, and ginger.'),
(44, 2, 'Pour in milk and let it boil for a few minutes.'),
(44, 3, 'For pakoras, mix besan, salt, and spices in a bowl.'),
(44, 4, 'Add water and mix well to form a batter.'),
(44, 5, 'Dip sliced potatoes and spinach in the batter to coat them.'),
(44, 6, 'Fry the pakoras in hot oil until golden brown and serve hot with chai.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(45, 1, 'To make the dalgona mixture, whisk together coffee, sugar, and water in a bowl until soft peaks form.'),
(45, 2, 'For iced coffee, add the dalgona mixture to cold milk. For hot coffee, mix it with hot milk.'),
(45, 3, 'Your dalgona coffee is ready to serve.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(46, 1, 'Boil your macaroni until al dente.'),
(46, 2, 'In a pan, add butter and flour, then sauté for a minute.'),
(46, 3, 'Add milk in batches while stirring continuously.'),
(46, 4, 'Add salt, pepper, chili flakes, and oregano.'),
(46, 5, 'Mix in the pasta and cheese, and let it cook for a few minutes.'),
(46, 6, 'In a baking tray, layer the pasta and cheese alternately, then bake in the oven until the cheese melts.'),
(46, 7, 'Remove from the oven and let it cool slightly.'),
(46, 8, 'Your mac and cheese is ready to be served.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(47, 1, 'In a bowl, combine oats, milk, and a sweetener of your choice. Let it sit for a few hours or overnight.'),
(47, 2, 'The next day, top it with chocolate chips, berries, nuts, and seeds, then enjoy.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(48, 1, 'In a bowl, mix chia seeds, milk, a sweetener of your choice, and cocoa powder.'),
(48, 2, 'Refrigerate for a few hours or overnight.'),
(48, 3, 'Top it with cocoa chips, berries, fruits, nuts, and seeds. Your chia pudding is ready to serve.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(49, 1, 'Dice all your vegetables and set them aside.'),
(49, 2, 'Prepare the guacamole.'),
(49, 3, 'In a baking dish, layer the nachos, then add chopped tomatoes, onions, and chilies.'),
(49, 4, 'Sprinkle cheese on top and broil in the oven until the cheese melts.'),
(49, 5, 'Serve with sour cream and guacamole.');

INSERT INTO instructions (recipe_id, step_number, instruction) VALUES
(50, 1, 'In a pressure cooker, add rice, moong dal, turmeric, salt, and ghee.'),
(50, 2, 'Cook until 5 whistles, then serve hot with extra ghee on top.');



