create database pantrychef;
use pantrychef;

CREATE TABLE ingredients (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
category VARCHAR(255) NOT NULL
);

insert into ingredients (name,category) values
('Tomato','Vegetables and Greens'),
('Onion','Vegetables and Greens'),
('Potato','Vegetables and Greens'),
('Capsicum','Vegetables and Greens'),
('Spinach','Vegetables and Greens'),
('Carrot','Vegetables and Greens'),
('Beans','Vegetables and Greens'),
('Broccoli','Vegetables and Greens'),
('Chilli','Vegetables and Greens'),
('Garlic','Vegetables and Greens'),
('Ginger','Vegetables and Greens'),
('Mushroom','Vegetables and Greens'),
('Spinach','Vegetables and Greens'),
('Coriander','Vegetables and Greens'),
('Lettuce','Vegetables and Greens'),
('Fenugreek Leaves','Vegetables and Greens'),
('Green Onions','Vegetables and Greens'),
('Cabbage','Vegetables and Greens'),
('Celery','Vegetables and Greens'),
('Beetroot','Vegetables and Greens'),
('Apple','Fruits'),
('Orange','Fruits'),
('Banana','Fruits'),
('Avocado','Fruits'),
('Mango','Fruits'),
('Lemon','Fruits'),
('Plum','Fruits'),
('Coconut','Fruits'),
('Strawberry','Fruits'),
('Raspberry','Fruits'),
('Blueberry','Fruits'),
('Kiwi','Fruits'),
('Pineapple','Fruits'),
('Cherry','Fruits'),
('Pomegranate','Fruits'),
('Coconut','Fruits'),
('Raisins','Fruits'),
('Pear','Fruits'),
('Passion Fruit','Fruits'),
('Sweet Lime','Fruits'),
('Almonds','Nuts and Seeds'),
('Cashews','Nuts and Seeds'),
('Walnuts','Nuts and Seeds'),
('Raisins','Nuts and Seeds'),
('Hazelnuts','Nuts and Seeds'),
('Pistachio','Nuts and Seeds'),
('Prunes','Nuts and Seeds'),
('Pecans','Nuts and Seeds'),
('Pumpkin Seeds','Nuts and Seeds'),
('Sesame Seeds','Nuts and Seeds'),
('Sunflower Seeds','Nuts and Seeds'),
('Chia Seeds','Nuts and Seeds'),
('Macadamia Nuts','Nuts and Seeds'),
('Anjeer','Nuts and Seeds'),
('Apricot','Nuts and Seeds'),
('Peanuts','Nuts and Seeds'),
('Pine Nuts','Nuts and Seeds'),
('Melon Seeds','Nuts and Seeds'),
('PoppySeeds','Nuts and Seeds'),
('Flax Seeds','Nuts and Seeds'),
('Milk','Dairy'),
('Eggs','Dairy'),
('Fresh Cream','Dairy'),
('Whipped Cream','Dairy'),
('Butter','Dairy'),('Yogurt','Dairy'),
('Buttermilk','Dairy'),
('Cream Cheese','Dairy'),
('Mozzarella Cheese','Dairy'),
('Cheddar Cheese','Dairy'),
('Milk Powder','Dairy'),
('Parmesan Cheese','Dairy'),
('Feta Cheese','Dairy'),
('Sour Cream','Dairy'),
('Greek Yogurt','Dairy'),
('White Sugar','Sugars and Sweetners'),
('Brown Sugar','Sugars and Sweetners'),
('Sweetened Condensed Milk','Sugars and Sweetners'),
('Honey','Sugars and Sweetners'),
('Maple Syrup','Sugars and Sweetners'),
('Stevia','Sugars and Sweetners'),
('Coconut Sugar','Sugars and Sweetners'),
('Jaggery','Sugars and Sweetners'),
('Caramel Syrup','Sugars and Sweetners'),
('Chocolate Syrup','Sugars and Sweetners'),
('Salt','Herbs and Spices'),
('Black Pepper','Herbs and Spices'),
('Chilli powder','Herbs and Spices'),
('Turmeric','Herbs and Spices'),
('Oregano','Herbs and Spices'),
('Chilli Flakes','Herbs and Spices'),
('Peri-Peri','Herbs and Spices'),
('Garlic Powder','Herbs and Spices'),
('Onion Powder','Herbs and Spices'),
('Garam Masala','Herbs and Spices'),
('Cumin Powder','Herbs and Spices'),
('Thyme','Herbs and Spices'),
('Rosemary','Herbs and Spices'),
('Mixed Herbs','Herbs and Spices'),
('Cajun Seasoning','Herbs and Spices'),
('Taco Seasoning','Herbs and Spices'),
('Cinnamon','Herbs and Spices'),
('Cloves','Herbs and Spices'),
('Cardamom','Herbs and Spices'),
('Bay Leaf','Herbs and Spices'),
('Almond Milk','Dairy Free and Meat Substitutes'),
('Oat Milk','Dairy Free and Meat Substitutes'),
('Tofu','Dairy Free and Meat Substitutes'),
('Soy Milk','Dairy Free and Meat Substitutes'),
('Almond Butter','Dairy Free and Meat Substitutes'),
('Coconut Cream','Dairy Free and Meat Substitutes'),
('Tempeh','Dairy Free and Meat Substitutes'),
('Coconut Milk','Dairy Free and Meat Substitutes'),
('Cashew Butter','Dairy Free and Meat Substitutes'),
('Pistachio Butter','Dairy Free and Meat Substitutes'),
('White Rice','Grains and Cereals'),
('Semolina','Grains and Cereals'),
('Oats','Grains and Cereals'),
('Wheat','Grains and Cereals'),
('Brown Rice','Grains and Cereals'),
('Qunioa','Grains and Cereals'),
('Moong Dal','Legumes'),
('Chana Dal','Legumes'),
('Urad Dal','Legumes'),
('Toor Dal','Legumes'),
('Moong','Legumes'),
('Black Chana','Legumes'),
('Chickpea','Legumes'),
('Rajma','Legumes'),
('Masoor Dal','Legumes'),
('Moong Dal','Legumes'),
('Lobia Beans','Legumes'),
('Oil','Oils and Fats'),
('Ghee','Oils and Fats'),
('Butter','Oils and Fats'),
('Olive Oil','Oils and Fats'),
('Mayonaise','Dressings and Vinegars'),
('White vinegar','Dressings and Vinegars'),
('Balsamic Vinegar','Dressings and Vinegars'),
('Sweet Chilli Sauce','Dressings and Vinegars'),
('Soy Sauce','Dressings and Vinegars'),
('Green Chilli Sauce','Dressings and Vinegars'),
('Tomato Ketchup','Dressings and Vinegars'),
('Pizza Pasta Sauce','Sauces Spreads and Dips'),
('Bbq Sauce','Sauces Spreads and Dips'),
('Pesto Sauce','Sauces Spreads and Dips'),
('Harissa Sauce','Sauces Spreads and Dips'),
('Cheese Sauce','Sauces Spreads and Dips'),
('Salsa','Sauces Spreads and Dips'),
('Tahini','Sauces Spreads and Dips'),
('Mustard Sauce','Sauces Spreads and Dips'),
('Schezwan Sauce','Sauces Spreads and Dips'),
('Chipotle Sauce','Sauces Spreads and Dips'),
('Flour','Baking'),
('Vanilla Extract','Baking'),
('Baking Powder','Baking'),
('Baking Soda','Baking'),
('Cornstarch','Baking'),
('Chocolate','Baking'),
('Cookie','Baking'),
('Cocoa powder','Baking'),
('Coffee','Baking'),
('Coconut','Baking'),
('Pasta','Packaged Foods'),
('Noodles','Packaged Foods'),
('Poha','Packaged Foods'),
('Murmura','Packaged Foods'),
('Bread Crumbs','Packaged Foods'),
('Bread','Packaged Foods');
